services:
  arr-guard:
    image: meinya/arr-guard:latest
    restart: unless-stopped
    environment:
      MODE: "subtitles" #serve #subtitles #unmatched
      LISTEN_ADDR: ":8080"
      FFPROBE_PATH: "/usr/local/bin/ffprobe"
      SONARR_URL: "http://sonarr:8989"
      SONARR_API_KEY: "replace-me"
      RADARR_URL: "http://radarr:7878"
      RADARR_API_KEY: "replace-me"
      DRY_RUN: "false"
      UNMATCHED_PATH: "/var/lib/arr-guard/unmatched.json"
      UNMATCHED_EXCLUDE_DIRS: ""
      STATE_PATH: "/var/lib/arr-guard/state.json"
      MAX_ATTEMPTS: "6"
      WORKERS: "2"
      WEBHOOK_USERNAME: "replace-me"
      WEBHOOK_PASSWORD: "replace-me"
    ports:
      - "8080:8080"
    volumes:
      - /srv/media:/media:ro
      - /srv/arr-guard:/var/lib/arr-guard
